### ISSUE TITLE
Add GitHub action workflow to lint yaml

### ISSUE THREAD

**Issue by cognifloyd** [cognifloyd/st2_installer.ansible#12]
Need a GitHub actions workflow to run linters starting with yamllint.

Should run on every PR and every push to main branch. Bonus: make it work for all branches except those with prefix `ansible-st2-`.

**Comment by cognifloyd** [comment]
Basically, convert this circleci job into a GitHub actions based workflow:
https://github.com/cognifloyd/st2_installer.ansible/blob/ansible-st2-tracking/.circleci/config.yml

**Comment by cognifloyd** [comment]
This skips `ansible-st2-*` branches:
```yaml
on:
  - push:
      branches-ignore:
        - 'ansible-st2-*'
  - pull_request:
      branches-ignore:
        - 'ansible-st2-*'
```
