### ISSUE TITLE
Add dependencies collections cache

### ISSUE THREAD

**Issue by cognifloyd** [cognifloyd/st2_installer.ansible#14]
https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows

cache is restored with actions/cache. cache is snapshotted after successful workflow.

https://github.com/actions/cache

```
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/.ansible/collections/ansible_collections/
      !~/.ansible/collections/ansible_collections/*/st2_installer/
    key: collections-${{ hashFiles('galaxy.yml') }}
```

**Comment by cognifloyd** [comment]
For the docker based actions, `~` won't work. Need to use home as: `/home/runner/work/_temp/_github_home`

```
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/.ansible/collections/ansible_collections/
      !~/.ansible/collections/ansible_collections/*/st2_installer/
    key: collections-${{ hashFiles('galaxy.yml') }}

- name: Save dependencies for caching
  run: |
    cp -R /home/runner/work/_temp/_github_home/.ansible ~
```
